-- INSERT INTO users (user_name, user_pass) VALUES ('user', 'stevemcqueen');
-- INSERT INTO users (user_name, user_pass) VALUES ('admin', 'stevemcqueen');
-- INSERT INTO roles (role_name) VALUES ('user');
-- INSERT INTO roles (role_name) VALUES ('admin');
-- INSERT INTO user_roles (user_name, role_name) VALUES ('user', 'user');
-- INSERT INTO user_roles (user_name, role_name) VALUES ('admin', 'admin');